In [14]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.metrics import r2_score,confusion_matrix
from sklearn.linear_model import LinearRegression,Ridge,LogisticRegression
from sklearn.model_selection import train_test_split

In [21]:
data = np.array([[3, -1.5,-1.9, -4.3],[0,4,-0.3, 2.1], [1,3.3,2, -5.4]])
data

array([[ 3. , -1.5, -1.9, -4.3],
       [ 0. ,  4. , -0.3,  2.1],
       [ 1. ,  3.3,  2. , -5.4]])

In [22]:
#Mean Removal
data_standardization = preprocessing.scale(data)
print("\nStandardized Data (found by data-data.mean/data.std)=\n",data_standardization)
print("Mean = ",data_standardization.mean(axis=0))
print("Std Deviation =",data_standardization.std(axis=0))

print("\nMean is almost 0 and std is 1")


Standardized Data (found by data-data.mean/data.std)=
 [[ 1.33630621 -1.40451644 -1.14533633 -0.53423728]
 [-1.06904497  0.84543708 -0.14577008  1.40111286]
 [-0.26726124  0.55907936  1.29110641 -0.86687558]]
Mean =  [ 5.55111512e-17 -1.11022302e-16 -1.48029737e-16 -7.40148683e-17]
Std Deviation = [1. 1. 1. 1.]

Mean is almost 0 and std is 1


In [23]:
#Scaling
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print("\nMin-Max Scaled Data =\n",data_scaled)


Min-Max Scaled Data =
 [[1.         0.         0.         0.14666667]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 1.         0.        ]]


In [33]:
#Normalization
data_normalized = preprocessing.normalize(data,norm='l1')
print("\nNormalized Data =\n",data_normalized)


Normalized Data =
 [[ 0.28037383 -0.14018692 -0.17757009 -0.40186916]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.08547009  0.28205128  0.17094017 -0.46153846]]


In [40]:
#Binarization
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print("\nBinarized Data =\n",data_binarized)


Binarized Data =
 [[1. 0. 0. 0.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]


In [55]:
#Label Encoding
car_classes = ['bmw','mercedez','porche','jaguar','rollsroyce']
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(car_classes)
test_cars = ['porche','jaguar','bmw','porche']
print("Input Classes =",test_cars)
print("Encoded Labels =",label_encoder.transform(test_cars))

Input Classes = ['porche', 'jaguar', 'bmw', 'porche']
Encoded Labels = [3 1 0 3]


In [56]:
#One Hot Encoding